CREATE TABLE NEW_ORDER
(
ORDER_ID INT NOT NULL,
ORDER_NUMBER VARCHAR(15) NOT NULL,
TOTAL_PRICE  NUMERIC (5,2) NOT NULL,
STATUS      VARCHAR(40)     NOT NULL,
DELIVERY_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
ORDER_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
CLIENT_ID INT NOT NULL,
RESTAURANT_ID INT NOT NULL,
ORDER_DETAIL_ID INT NOT NULL,

PRIMARY KEY (ORDER_ID),
    UNIQUE (ORDER_NUMBER),
    CONSTRAINT fk_order_client
        FOREIGN KEY (client_id)
            REFERENCES client (client_id),
    CONSTRAINT fk_order_restaurant
        FOREIGN KEY (restaurant_id)
            REFERENCES restaurant (restaurant_id),
    CONSTRAINT fk_order_order_detail
        FOREIGN KEY (order_detail_id)
            REFERENCES order_detail (order_detail_id)
);