CREATE TABLE CLIENT
(
    CLIENT_ID   SERIAL      NOT NULL,
    NAME        VARCHAR(32) NOT NULL,
    SURNAME     VARCHAR(32) NOT NULL,
    PHONE       VARCHAR(32) NOT NULL,
    ADDRESS_ID  INT         NOT NULL,
    EMAIL       VARCHAR(32) NOT NULL,
    PASSWORD    VARCHAR(20) NOT NULL,
    PRIMARY KEY (CLIENT_ID),
    UNIQUE (EMAIL),
        CONSTRAINT FK_CLIENT_ADDRESS
            FOREIGN KEY (ADDRESS_ID)
                REFERENCES ADDRESS (ADDRESS_ID)
);