CREATE TABLE RESTAURANT_OWNER
(
    RESTAURANT_OWNER_ID   SERIAL      NOT NULL,
    NAME        VARCHAR(32) NOT NULL,
    SURNAME     VARCHAR(32) NOT NULL,
    EMAIL       VARCHAR(32) NOT NULL,
    PASSWORD    VARCHAR(20) NOT NULL,
    PRIMARY KEY (RESTAURANT_OWNER_ID),
    UNIQUE (EMAIL)
);
