CREATE TABLE CLIENT
(
    CLIENT_ID   SERIAL      NOT NULL,
    NAME        VARCHAR(64) NOT NULL,
    SURNAME     VARCHAR(64) NOT NULL,
    PHONE       VARCHAR(20) NOT NULL,
    ADDRESS_ID  INT         NOT NULL,
    EMAIL       VARCHAR(255) NOT NULL,
    CART_ID     INT         NOT NULL,
    PRIMARY KEY (CLIENT_ID),
    UNIQUE (EMAIL),
        CONSTRAINT FK_CLIENT_ADDRESS
            FOREIGN KEY (ADDRESS_ID)
                REFERENCES ADDRESS (ADDRESS_ID),
        CONSTRAINT FK_CLIENT_CART
            FOREIGN KEY (CART_ID)
                REFERENCES CART (CART_ID)
);