CREATE TABLE RESTAURANT_OWNER
(
    RESTAURANT_OWNER_ID   SERIAL      NOT NULL,
    NAME        VARCHAR(64) NOT NULL,
    SURNAME     VARCHAR(64) NOT NULL,
    PHONE       VARCHAR(20) NOT NULL,
    EMAIL       VARCHAR(255) NOT NULL,
    PRIMARY KEY (RESTAURANT_OWNER_ID),
    UNIQUE (EMAIL)

);
