CREATE TABLE RESTAURANT
(
    RESTAURANT_ID        SERIAL      NOT NULL,
    NAME                 VARCHAR(32) NOT NULL,
    RESTAURANT_OWNER_ID  INT         NOT NULL,
    DELIVERY_AREA        INT         NOT NULL,
    PRIMARY KEY (RESTAURANT_ID),
    CONSTRAINT FK_RESTAURANT_ADDRESS
            FOREIGN KEY (ADDRESS_ID)
                REFERENCES ADDRESS (ADDRESS_ID),
    CONSTRAINT FK_RESTAURANT_RESTAURANT_OWNER
            FOREIGN KEY (RESTAURANT_OWNER_ID)
                REFERENCES RESTAURANT_OWNER (RESTAURANT_OWNER_ID)
);
