CREATE TABLE MENU
(
    MENU_ID             SERIAL       NOT NULL,
    DESCRIPTION         VARCHAR(100) NOT NULL,
    RESTAURANT_ID INT          NOT NULL,
    PRIMARY KEY (MENU_ID),
    CONSTRAINT FK_MENU_RESTAURANT
            FOREIGN KEY (RESTAURANT_ID)
                REFERENCES RESTAURANT (RESTAURANT_ID),
);
