CREATE TABLE RESTAURANT
(
    RESTAURANT_ID        INT      NOT NULL,
    NAME                 VARCHAR(64) NOT NULL,
    RESTAURANT_OWNER_ID  INT         NOT NULL,
    PRIMARY KEY (RESTAURANT_ID),
    CONSTRAINT FK_RESTAURANT_RESTAURANT_OWNER
            FOREIGN KEY (RESTAURANT_OWNER_ID)
                REFERENCES RESTAURANT_OWNER (RESTAURANT_OWNER_ID)
);
