CREATE TABLE NEW_ORDER
(
    NEW_ORDER_ID        SERIAL                      NOT NULL,
    CLIENT_ID           INT                         NOT NULL,
    TOTAL AMOUNT        NUMERIC(4,2)                NOT NULL,
    ORDERED_DATE        TIMESTAMP WITH TIME ZONE    NOT NULL,
    COMPLETED_DATE      TIMESTAMP WITH TIME ZONE    NOT NULL,
    PRIMARY KEY (NEW_ORDER_ID),
    CONSTRAINT FK_NEW_ORDER_CLIENT_ID
            FOREIGN KEY (CLIENT_ID)
                REFERENCES CLIENT (CLIENT_ID)
);
