CREATE TABLE ORDER_ITEM
(
    ORDER_ITEM_ID       SERIAL       NOT NULL,
    NEW_ORDER_ID        VARCHAR(20)  NOT NULL,
    MENU_ID             INT          NOT NULL,
    QUANTITY            INT          NOT NULL,
    PRIMARY KEY (ORDER_ITEM_ID),
    CONSTRAINT FK_ORDER_ITEM_NEW_ORDER
            FOREIGN KEY (NEW_ORDER_ID)
                REFERENCES NEW_ORDER (NEW_ORDER_ID)
    CONSTRAINT FK_ORDER_ITEM_MENU
            FOREIGN KEY (MENU_ID)
                REFERENCES MENU (MENU_ID)
);
