CREATE TABLE RESTAURANT_STREET
(
 RESTAURANT_STREET_ID      SERIAL       NOT NULL,
 RESTAURANT_ID             INT          NOT NULL,
 STREET_ID                 INT          NOT NULL,
 PRIMARY KEY(RESTAURANT_STREET_ID),
 CONSTRAINT FK_RESTAURANT_STREET_RESTAURANT
          FOREIGN KEY (RESTAURANT_ID)
             REFERENCES RESTAURANT (RESTAURANT_ID),
 CONSTRAINT FK_RESTAURANT_STREET_STREET
          FOREIGN KEY (STREET_ID)
             REFERENCES STREET (STREET_ID)
);

