

insert into client (name, surname, phone, email)
values
('John', 'Doe', '123-456-789', 'john.doe@example.com'),
('Alice', 'Smith', '987-654-321', 'alice.smith@example.com'),
('Bob', 'Johnson', '555-555-555', 'bob.johnson@example.com');

insert into restaurant_owner(name, surname, phone, email)
values
('Stefan', 'Stefanowicz','123-456-789','stefan@miastowa.com'),
('Agata', 'Agrafka','987-654-321', 'agata@victi.com' ),
('Tomasz', 'Tomaszewski',  '555-555-555','tomasz@tomani.com');

insert into address (country, city, street, number) values ('Polska', 'Warszawa', 'Złota','1');
insert into address (country, city, street, number) values ('Polska', 'Warszawa', 'Srebrna','2');
insert into address (country, city, street, number) values ('Polska', 'Warszawa', 'Brązowa','3');

INSERT INTO RESTAURANT(NAME, EMAIL, PHONE, ADDRESS_ID, RESTAURANT_OWNER_ID)
VALUES
('Miastowa','miastowa@gmail.com', '666 777 888', 1 , 1),
('Victi', 'victi@gmail.com', '777 888 999', 2, 2),
('Tomani', 'tomani@gmail.com', '444 555 666', 3, 3);

INSERT INTO STREET(NAME)
VALUES
('1 Praskiego Pułku WP'),
('Aleja 3 Maja'),
('11 Listopada'),
('29 Listopada'),
('gen. Romana Abrahama'),
('Akademicka'),
('gen. Władysława Andersa'),
('Mordechaja Anielewicza'),
('Aleja Armii Ludowej'),
('Marcella Bacciarellego'),
('Jana Sebastiana Bacha'),
('Bagatela'),
('Bagno'),
('Baletowa'),
('Stefana Banacha'),
('Barcicka'),
('Barokowa'),
('Barska'),
('Juliana Bartoszewicza'),
('Bartycka'),
('Aleja Józefa Becka'),
('Bednarska'),
('Belgijska'),
('Belgradzka'),
('Belwederska'),
('Józefa Bema'),
('Biała'),
('Białobrzeska'),
('Białoskórnicza'),
('Białostocka'),
('Bielańska'),
('Biruty'),
('Blaszana'),
('Bliska'),
('Gabriela Piotra Boduena'),
('Bohaterów Warszawy'),
('Bonifraterska'),
('gen. Tadeusza Bora-Komorowskiego'),
('Borzymowska'),
('Bracka'),
('Władysława Broniewskiego'),
('Browarna'),
('Bródnowska'),
('Brylowska'),
('Brzozowa'),
('Bugaj'),
('Burakowska'),
('Burmistrzowska'),
('Canaletta'),
('Celna'),
('Tytusa Chałubińskiego'),
('Chełmska'),
('Chłodna'),
('Chmielna'),
('Chocimska'),
('Chodakowska'),
('Fryderyka Chopina'),
('Ciasna'),
('Cicha'),
('Ciepła'),
('Jana Ciszewskiego'),
('Tadeusza Czackiego'),
('Bronisława Czecha'),
('Czerniakowska'),
('Czerwonego Krzyża'),
('Człuchowska'),
('Czynszowa'),
('Daleka'),
('Daniłowiczowska'),
('Dawna'),
('Dereniowa'),
('Długa'),
('Jana Długosza'),
('Franciszka Ksawerego Dmochowskiego'),
('Dobra'),
('Dolina Służewiecka'),
('Dolna'),
('Domaniewska'),
('Dowcip'),
('Drewniana'),
('Drewnicka'),
('Dynasy'),
('Działdowska'),
('Dziekania'),
('Dzielna'),
('Dzika'),
('Elektoralna'),
('Elektryczna'),
('Elsterska'),
('Estońska'),
('Fabryczna'),
('gen. Augusta Emila Fieldorfa „Nila”'),
('Filtrowa'),
('Floriańska'),
('Flory'),
('Foksal'),
('Folwarczna'),
('Franciszkańska'),
('Francuska'),
('Frascati'),
('Aleksandra Fredry'),
('Freta'),
('Furmańska'),
('Jurija Gagarina'),
('Indiry Gandhi'),
('Garbarska'),
('Gdańska'),
('Gęsta'),
('Edwarda Gibalskiego'),
('Gliniana'),
('Głębocka'),
('Głucha'),
('Gocławska'),
('Górczewska'),
('Górnośląska'),
('Wojciecha Górskiego'),
('Grabowska'),
('Grajewska'),
('Graniczna'),
('Grażyny'),
('Grenadierów'),
('Grochowska'),
('Kazimierza Grodeckiego'),
('Grodzieńska'),
('Grodzka'),
('Groszowicka'),
('Artura Grottgera'),
('Grójecka'),
('Grzybowska'),
('Gwiaździsta'),
('Aleja Harcerzy Rzeczypospolitej'),
('Handlowa'),
('Hipoteczna'),
('Józefa Hoene-Wrońskiego'),
('Stanisława Hozjusza'),
('Hoża'),
('Hrubieszowska'),
('Humańska'),
('Adama Idźkowskiego'),
('Inflancka'),
('Inżynierska'),
('Jadowska'),
('Jagiellońska'),
('Jaktorowska'),
('Jana Kazimierza'),
('Jana Olbrachta'),
('Aleja Jana Pawła II'),
('Stefana Jaracza'),
('Jakuba Jasińskiego'),
('Jasna'),
('Jezuicka'),
('Kazimierza Jeżewskiego'),
('Kacza'),
('Kaliska'),
('Kamienne Schodki'),
('Kamionkowska'),
('Kanonia'),
('Kapitulna'),
('Karczunkowska'),
('Karmelicka'),
('Karolkowa'),
('Karowa'),
('Jana Kasprowicza'),
('Marcina Kasprzaka'),
('Katowicka'),
('Kępna'),
('Kijowska'),
('Jana Kilińskiego'),
('Kleczewska'),
('Klonowa'),
('Kłopot'),
('ks. Ignacego Kłopotowskiego'),
('Kobielska'),
('Kolejowa'),
('Kolska'),
('Kołowa'),
('Aleja Komisji Edukacji Narodowej'),
('Konopacka'),
('Konwiktorska'),
('Mikołaja Kopernika'),
('Korkowa'),
('Koszykowa'),
('Kościelna'),
('Kościuszkowców'),
('Kowelska'),
('Koźla'),
('Aleja Krakowska'),
('Krakowskie Przedmieście'),
('Zygmunta Krasińskiego'),
('Kredytowa'),
('Krochmalna'),
('Królewska'),
('Krucza'),
('Krzywe Koło'),
('Krzywopoboczna'),
('Książęca'),
('Księcia Janusza'),
('Kubusia Puchatka'),
('Mariana Langiewicza'),
('Lekarska'),
('Leszno'),
('Letnia'),
('Józefa Lewartowskiego'),
('Williama Heerleina Lindleya'),
('Litewska'),
('Lubelska'),
('Ludna'),
('Ludwiki'),
('Lwowska'),
('Łazienkowska'),
('Łochowska'),
('Łukowska'),
('Antoniego Mackiewicza'),
('Antoniego Malczewskiego'),
('Markowska'),
('Marsa'),
('Marymoncka'),
('Marynarska'),
('Marywilska'),
('Jana Matejki'),
('Mazowiecka'),
('Józefa Mehoffera'),
('Janusza Meissnera'),
('Józefa Mianowskiego'),
('Adama Mickiewicza'),
('Miedziana'),
('Międzyborska'),
('Międzynarodowa'),
('Międzyparkowa'),
('Miła'),
('Mińska'),
('Mlądzka'),
('Młynarska'),
('Modlińska'),
('Zygmunta Modzelewskiego'),
('Mysia'),
('Myśliwiecka'),
('Ludwika Narbutta'),
('Aleja Niepodległości'),
('Niska'),
('Stanisława Noakowskiego'),
('Alfreda Nobla'),
('Nowiniarska'),
('Nowogrodzka'),
('Nowolipie'),
('Nowolipki'),
('Nowomiejska'),
('Nowoursynowska'),
('Nowowiejska'),
('Nowy Zjazd'),
('Obozowa'),
('Okopowa'),
('Oboźna'),
('Obrońców'),
('Wojciecha Oczki'),
('Ogrodowa'),
('Okólnik'),
('Okrąg'),
('Stefana Okrzei'),
('Olszowa'),
('Opaczewska'),
('Juliana Konstantego Ordona'),
('Ordynacka'),
('Orla'),
('Ostrobramska'),
('Oszmiańska'),
('Płatnicza'),
('Panieńska'),
('Pańska'),
('Paryska'),
('Pawia'),
('Icchoka Lejba Pereca'),
('Piesza'),
('Piękna'),
('rtm. Witolda Pileckiego'),
('Piwna'),
('Emilii Plater'),
('Filipiny Płaskowickiej'),
('Płochocińska'),
('Płocka'),
('Podskarbińska'),
('Pokorna'),
('Polna'),
('Aleja Polski Walczącej'),
('Połczyńska'),
('Powsińska'),
('Powstańców Śląskich'),
('Poznańska'),
('Pratulińska'),
('Prosta'),
('Próżna'),
('Prudnicka'),
('Pruszkowska'),
('Aleja Prymasa Tysiąclecia'),
('Przy Bażantarni'),
('Aleja Przyjaciół'),
('Przyokopowa'),
('Przyrynek'),
('Puławska'),
('Pułkowa'),
('Racławicka'),
('Radzymińska'),
('Rajców'),
('Rakowiecka'),
('Raszyńska'),
('Ratuszowa'),
('Redutowa'),
('Aleja Jana Rodowicza „Anody”'),
('Wilhelma Konrada Roentgena'),
('Rolna'),
('Jana Rosoła'),
('Rozbrat'),
('Aleja Róż'),
('Rybaki'),
('Rycerska'),
('Aleja Rzeczypospolitej'),
('Wincentego Rzymowskiego'),
('Samborska'),
('Romana Sanguszki'),
('Saska'),
('Aleja Ireny Sendlerowej'),
('Sewerynów'),
('Siedmiogrodzka'),
('Henryka Sienkiewicza'),
('Sienna'),
('Józefa Sierakowskiego'),
('Skalbmierska'),
('ks. Piotra Skargi'),
('Skaryszewska'),
('Zygmunta Słomińskiego'),
('Juliusza Słowackiego'),
('Smocza'),
('Smoleńska'),
('Smolna'),
('Jana III Sobieskiego'),
('Solec'),
('Aleja „Solidarności”'),
('Józefa Sowińskiego'),
('Spacerowa'),
('Spokojna'),
('Stalowa'),
('Aleja Stanów Zjednoczonych'),
('Stara'),
('Stare Nalewki'),
('Stefana Starzyńskiego'),
('Stawki'),
('Stryjeńskich'),
('Strzelecka'),
('Pawła Suzina'),
('Syreny'),
('Szara'),
('Szczęśliwicka'),
('Szczygla'),
('Szeroki Dunaj'),
('Szpitalna'),
('Aleja Jana Chrystiana Szucha'),
('Szwedzka'),
('Szwoleżerów'),
('Jana i Jędrzeja Śniadeckich'),
('św. Barbary'),
('św. Wincentego'),
('Światowida'),
('Świętojańska'),
('Świętojerska'),
('Świętokrzyska'),
('Świętych Cyryla i Metodego'),
('Targowa'),
('Tarniny'),
('Tłomackie'),
('Towarowa'),
('Trakt Leśny'),
('Trakt Lubelski'),
('Trocka'),
('Twarda'),
('Tykocińska'),
('Aleja Tysiąclecia'),
('Aleje Ujazdowskie'),
('Władysława Umińskiego'),
('Uniwersytecka'),
('Walecznych'),
('Waliców'),
('Wał Miedzeszyński'),
('Wał Zawadowski'),
('Wałbrzyska'),
('Warecka'),
('Ludwika Waryńskiego'),
('Aleja Jerzego Waszyngtona'),
('Wawelska'),
('Wąski Dunaj'),
('Wąwozowa'),
('Wenedów'),
('Wiatraczna'),
('Widok'),
('Wiejska'),
('Aleja Wielkopolski'),
('Wiertnicza'),
('Wiktorska'),
('Aleja Wilanowska'),
('Wilanowska'),
('Wilcza');

INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,1);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,2);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,3);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,4);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,5);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,6);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,7);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,8);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,9);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,10);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,11);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,12);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,13);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,14);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,15);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,16);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,17);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,18);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,19);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,20);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,21);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,22);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,23);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,24);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,25);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,26);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,27);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,28);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,29);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,30);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,31);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,32);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,33);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,34);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,35);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,36);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,37);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,38);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,39);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,40);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,41);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,42);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,43);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,44);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,45);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,46);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,47);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,48);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,49);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,50);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,51);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,52);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,53);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,54);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,55);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,56);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,57);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,58);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,59);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,60);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,61);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,62);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,63);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,64);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,65);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,66);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,67);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,68);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,69);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,70);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,71);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,72);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,73);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,74);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,75);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,76);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,77);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,78);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,79);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,80);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,81);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,82);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,83);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,84);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,85);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,86);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,87);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,88);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,89);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,90);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,91);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,92);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,93);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,94);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,95);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,96);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,97);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,98);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,99);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,100);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,101);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,102);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,103);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,104);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,105);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,106);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,107);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,108);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,109);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,110);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,111);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,112);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,113);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,114);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,115);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,116);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,117);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,118);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,119);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,120);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,121);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,122);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,123);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,124);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,125);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,126);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,127);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,128);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,129);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,130);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,131);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,132);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,133);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,134);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,135);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,136);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,137);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,138);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,139);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,140);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,141);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,142);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,143);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,144);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,145);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,146);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,147);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,148);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,149);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,150);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,151);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,152);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,153);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,154);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,155);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,156);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,157);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,158);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,159);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,160);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,161);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,162);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,163);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,164);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,165);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,166);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,167);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,168);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,169);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,170);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,171);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,172);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,173);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,174);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,175);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,176);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,177);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,178);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,179);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,180);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,181);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,182);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,183);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,184);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,185);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,186);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,187);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,188);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,189);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,190);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,191);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,192);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,193);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,194);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,195);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,196);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,197);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,198);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,199);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,200);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,201);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,202);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,203);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,204);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,205);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,206);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,207);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,208);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,209);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,210);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,211);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,212);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,213);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,214);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,215);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,216);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,217);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,218);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,219);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,220);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,221);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,222);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,223);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,224);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,225);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,226);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,227);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,228);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,229);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,230);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,231);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,232);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,233);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,234);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,235);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,236);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,237);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,238);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,239);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,240);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,241);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,242);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,243);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,244);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,245);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,246);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,247);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,248);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,249);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,250);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,251);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,252);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,253);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,254);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,255);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,256);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,257);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,258);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,259);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,260);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,261);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,262);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,263);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,264);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,265);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,266);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,267);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,268);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,269);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,270);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,271);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,272);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,273);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,274);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,275);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,276);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,277);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,278);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,279);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,280);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,281);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,282);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,283);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,284);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,285);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,286);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,287);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,288);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,289);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,290);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,291);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,292);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,293);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,294);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,295);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,296);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,297);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,298);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,299);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,300);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,301);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,302);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,303);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,304);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,305);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,306);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,307);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,308);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,309);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,310);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,311);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,312);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,313);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,314);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,315);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,316);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,317);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,318);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,319);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,320);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,321);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,322);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,323);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,324);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,325);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,326);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,327);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,328);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,329);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,330);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,331);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,332);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,333);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,334);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,335);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,336);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,337);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,338);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,339);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,340);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,341);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,342);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,343);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,344);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,345);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,346);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,347);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,348);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,349);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,350);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,351);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,352);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,353);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,354);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,355);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,356);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,357);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,358);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,359);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,360);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,361);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,362);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,363);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,364);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,365);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,366);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,367);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,368);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,369);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,370);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,371);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,372);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,373);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,374);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,375);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,376);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,377);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,378);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,379);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,380);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,381);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,382);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,383);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,384);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,385);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,386);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,387);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,388);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,389);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,390);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,391);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,392);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,393);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,394);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,395);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,396);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,397);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,398);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,399);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (1,400);

INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,1);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,2);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,3);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,4);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,5);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,6);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,7);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,8);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,9);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,10);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,11);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,12);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,13);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,14);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,15);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,16);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,17);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,18);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,19);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,20);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,21);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,22);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,23);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,24);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,25);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,26);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,27);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,28);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,29);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,30);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,31);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,32);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,33);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,34);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,35);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,36);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,37);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,38);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,39);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,40);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,41);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,42);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,43);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,44);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,45);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,46);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,47);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,48);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,49);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,50);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,51);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,52);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,53);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,54);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,55);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,56);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,57);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,58);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,59);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,60);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,61);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,62);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,63);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,64);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,65);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,66);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,67);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,68);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,69);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,70);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,71);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,72);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,73);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,74);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,75);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,76);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,77);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,78);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,79);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,80);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,81);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,82);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,83);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,84);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,85);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,86);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,87);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,88);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,89);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,90);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,91);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,92);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,93);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,94);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,95);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,96);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,97);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,98);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,99);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,100);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,101);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,102);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,103);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,104);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,105);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,106);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,107);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,108);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,109);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,110);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,111);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,112);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,113);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,114);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,115);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,116);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,117);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,118);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,119);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,120);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,121);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,122);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,123);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,124);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,125);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,126);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,127);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,128);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,129);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,130);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,131);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,132);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,133);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,134);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,135);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,136);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,137);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,138);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,139);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,140);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,141);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,142);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,143);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,144);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,145);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,146);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,147);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,148);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,149);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,150);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,151);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,152);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,153);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,154);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,155);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,156);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,157);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,158);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,159);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,160);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,161);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,162);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,163);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,164);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,165);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,166);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,167);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,168);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,169);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,170);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,171);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,172);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,173);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,174);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,175);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,176);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,177);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,178);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,179);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,180);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,181);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,182);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,183);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,184);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,185);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,186);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,187);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,188);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,189);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,190);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,191);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,192);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,193);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,194);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,195);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,196);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,197);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,198);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,199);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,200);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,201);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,202);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,203);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,204);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,205);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,206);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,207);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,208);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,209);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,210);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,211);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,212);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,213);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,214);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,215);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,216);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,217);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,218);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,219);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,220);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,221);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,222);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,223);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,224);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,225);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,226);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,227);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,228);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,229);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,230);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,231);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,232);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,233);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,234);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,235);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,236);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,237);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,238);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,239);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,240);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,241);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,242);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,243);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,244);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,245);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,246);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,247);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,248);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,249);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,250);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,251);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,252);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,253);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,254);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,255);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,256);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,257);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,258);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,259);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,260);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,261);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,262);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,263);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,264);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,265);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,266);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,267);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,268);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,269);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,270);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,271);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,272);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,273);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,274);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,275);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,276);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,277);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,278);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,279);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,280);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,281);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,282);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,283);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,284);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,285);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,286);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,287);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,288);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,289);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,290);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,291);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,292);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,293);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,294);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,295);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,296);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,297);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,298);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,299);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,300);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,301);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,302);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,303);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,304);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,305);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,306);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,307);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,308);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,309);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,310);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,311);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,312);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,313);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,314);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,315);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,316);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,317);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,318);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,319);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,320);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,321);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,322);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,323);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,324);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,325);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,326);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,327);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,328);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,329);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,330);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,331);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,332);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,333);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,334);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,335);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,336);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,337);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,338);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,339);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,340);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,341);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,342);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,343);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,344);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,345);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,346);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,347);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,348);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,349);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,350);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,351);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,352);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,353);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,354);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,355);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,356);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,357);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,358);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,359);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,360);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,361);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,362);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,363);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,364);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,365);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,366);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,367);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,368);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,369);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,370);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,371);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,372);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,373);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,374);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,375);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,376);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,377);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,378);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,379);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,380);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,381);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,382);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,383);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,384);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,385);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,386);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,387);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,388);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,389);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,390);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,391);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,392);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,393);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,394);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,395);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,396);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,397);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,398);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,399);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (2,400);

INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,1);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,2);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,3);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,4);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,5);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,6);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,7);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,8);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,9);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,10);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,11);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,12);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,13);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,14);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,15);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,16);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,17);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,18);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,19);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,20);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,21);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,22);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,23);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,24);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,25);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,26);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,27);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,28);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,29);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,30);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,31);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,32);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,33);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,34);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,35);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,36);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,37);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,38);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,39);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,40);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,41);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,42);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,43);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,44);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,45);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,46);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,47);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,48);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,49);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,50);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,51);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,52);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,53);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,54);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,55);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,56);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,57);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,58);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,59);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,60);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,61);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,62);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,63);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,64);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,65);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,66);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,67);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,68);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,69);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,70);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,71);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,72);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,73);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,74);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,75);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,76);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,77);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,78);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,79);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,80);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,81);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,82);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,83);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,84);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,85);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,86);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,87);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,88);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,89);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,90);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,91);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,92);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,93);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,94);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,95);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,96);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,97);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,98);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,99);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,100);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,101);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,102);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,103);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,104);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,105);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,106);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,107);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,108);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,109);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,110);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,111);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,112);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,113);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,114);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,115);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,116);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,117);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,118);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,119);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,120);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,121);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,122);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,123);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,124);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,125);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,126);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,127);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,128);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,129);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,130);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,131);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,132);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,133);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,134);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,135);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,136);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,137);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,138);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,139);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,140);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,141);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,142);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,143);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,144);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,145);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,146);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,147);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,148);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,149);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,150);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,151);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,152);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,153);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,154);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,155);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,156);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,157);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,158);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,159);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,160);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,161);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,162);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,163);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,164);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,165);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,166);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,167);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,168);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,169);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,170);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,171);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,172);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,173);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,174);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,175);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,176);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,177);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,178);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,179);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,180);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,181);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,182);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,183);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,184);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,185);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,186);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,187);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,188);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,189);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,190);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,191);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,192);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,193);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,194);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,195);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,196);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,197);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,198);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,199);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,200);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,201);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,202);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,203);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,204);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,205);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,206);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,207);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,208);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,209);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,210);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,211);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,212);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,213);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,214);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,215);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,216);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,217);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,218);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,219);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,220);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,221);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,222);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,223);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,224);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,225);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,226);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,227);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,228);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,229);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,230);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,231);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,232);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,233);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,234);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,235);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,236);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,237);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,238);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,239);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,240);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,241);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,242);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,243);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,244);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,245);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,246);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,247);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,248);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,249);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,250);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,251);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,252);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,253);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,254);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,255);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,256);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,257);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,258);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,259);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,260);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,261);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,262);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,263);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,264);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,265);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,266);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,267);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,268);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,269);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,270);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,271);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,272);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,273);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,274);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,275);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,276);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,277);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,278);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,279);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,280);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,281);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,282);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,283);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,284);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,285);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,286);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,287);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,288);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,289);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,290);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,291);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,292);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,293);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,294);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,295);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,296);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,297);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,298);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,299);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,300);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,301);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,302);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,303);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,304);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,305);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,306);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,307);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,308);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,309);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,310);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,311);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,312);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,313);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,314);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,315);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,316);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,317);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,318);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,319);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,320);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,321);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,322);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,323);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,324);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,325);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,326);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,327);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,328);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,329);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,330);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,331);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,332);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,333);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,334);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,335);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,336);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,337);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,338);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,339);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,340);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,341);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,342);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,343);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,344);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,345);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,346);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,347);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,348);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,349);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,350);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,351);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,352);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,353);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,354);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,355);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,356);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,357);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,358);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,359);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,360);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,361);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,362);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,363);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,364);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,365);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,366);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,367);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,368);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,369);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,370);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,371);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,372);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,373);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,374);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,375);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,376);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,377);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,378);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,379);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,380);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,381);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,382);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,383);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,384);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,385);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,386);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,387);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,388);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,389);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,390);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,391);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,392);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,393);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,394);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,395);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,396);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,397);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,398);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,399);
INSERT INTO RESTAURANT_STREET(RESTAURANT_ID, STREET_ID) VALUES (3,400);

INSERT INTO CATEGORY(NAME)
VALUES
('DESSERTS'), ( 'MAIN DISH'), ( 'SOUP'), ( 'DRINK');

insert into meal(name, category_ID, description, price, restaurant_id)
values
('Apple dumplings', 1, 'Delicious apple dumplings', 16.00, 1),
('Strawberry dumplings', 1, 'Strawberry strawberry dumplings', 15.00, 1),
('Orange dumplings', 1, 'Delicious orange dumplings', 20.00, 2),
('Pancakes with chocolate', 1, 'Delicious pancakes with chocolate', 27.00, 2),
('Pancakes with powdered sugar', 1, 'Delicious pancakes with powdered sugar', 15.00, 3),
('Pancakes with strawberries', 1, 'Delicious pancakes with strawberries', 16.00, 3),
('Pasta with cheese and spinach', 2, 'Delicious pasta with cheese and spinach', 30.00, 1),
('Chicken quarter with roasted potatoes', 2, 'Delicious Chicken quarter with roasted potatoes', 35.00, 1),
('Pasta with tuna and tomatoes', 2, 'Delicious pasta with tuna and tomatoes',27.00, 1),
('Chicken leg with potatoes', 2, 'Delicious chicken leg with potatoes', 35.00, 1),
('Pasta with tomatoes and basil', 2, 'Delicious pasta with tomatoes and basil', 26.00, 2),
('Pasta with tomatoes and cheese', 2, 'Delicious Pasta with tomatoes and cheese', 28.00, 3),
('Pasta with broccoli sauce', 2, 'Delicious pasta with broccoli sauce', 29.00, 2),
('Chicken with potatoes', 2, 'Delicious chicken with potatoes', 35.00, 3),
('Chicken with french fries', 2, 'Delicious chicken with fries', 35.00, 2),
('Pork chop with cabbage and mushrooms', 2, 'Delicious pork chop with cabbage and mushrooms', 35.00, 3),
('Tomato soup with noodles', 3, 'Delicious tomato soup with noodles', 15.00, 1),
('Broth with noodles', 3, 'Delicious broth with noodles', 15.00, 1),
('Krupnik', 3, 'Delicious krupnik', 15.00, 2),
('Vegetable soup', 3, 'Delicious vegetable soup', 15.00, 2),
('Ramen soup', 3, 'Delicious ramen soup', 15.00, 3),
('Coca-cola', 4, 'Delicious coca-cola', 7.00, 1),
('Apple juice', 4, 'Delicious apple juice', 7.00, 1),
('Fanta', 4, 'Delicious fanta', 7.00, 2),
('Orange juice', 4, 'Delicious orange juice', 7.00, 3),
('7up', 4, 'Delicious 7up', 7.00, 3),
('Ham and cheese sandwiches', 4, 'Delicious ham and cheese sandwiches', 10.00, 1),
('Panini with cheese', 4, 'Delicious panini with cheese', 10.00, 2),
('Salmon sandwiches', 4, 'Delicious salmon sandwiches', 9.00, 3),
('Sandwiches with egg paste', 4, 'Delicious sandwiches with egg paste', 9.00, 3);
